//------------------------------------------------------------------------------
//
//  DelphiStrife is a source port of the game Strife.
//
//  Based on:
//    - Linux Doom by "id Software"
//    - Chocolate Strife by "Simon Howard"
//    - DelphiDoom by "Jim Valavanis"
//
//  Copyright (C) 1993-1996 by id Software, Inc.
//  Copyright (C) 2005 Simon Howard
//  Copyright (C) 2010 James Haley, Samuel Villarreal
//  Copyright (C) 2004-2022 by Jim Valavanis
//
//  This program is free software; you can redistribute it and/or
//  modify it under the terms of the GNU General Public License
//  as published by the Free Software Foundation; either version 2
//  of the License, or (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program; if not, write to the Free Software
//  Foundation, inc., 59 Temple Place - Suite 330, Boston, MA
//  02111-1307, USA.
//
//  DESCRIPTION:
//  UMAPINFO support - Strife actor names
//
//------------------------------------------------------------------------------
//  Site  : https://sourceforge.net/projects/delphidoom/
//------------------------------------------------------------------------------

{$I Doom32.inc}

unit p_uactornames;

interface

uses
  info_h;

const
  NUMACTORNAMES = 357;
  ActorNames: array[0..NUMACTORNAMES - 1] of string[MOBJINFONAMESIZE] = (
    'FORCE FIELD GUARD',
    'MT_PLAYER',
    'WEAPON SMITH 4 TAN',
    'BAR KEEP 1 GOLD',
    'ARMORER 2 BRIGHT GREEN',
    'MEDIC 3 BLUE',
    'PEASANT TAN 1',
    'PEASANT TAN 2',
    'PEASANT TAN 3',
    'PEASANT RED 1',
    'PEASANT RED 2',
    'PEASANT RED 3',
    'PEASANT GRAY 1',
    'PEASANT GRAY 2',
    'PEASANT GRAY 3',
    'PEASANT RUST 1',
    'PEASANT RUST 2',
    'PEASANT RUST 3',
    'PEASANT DGREEN 1',
    'PEASANT DGREEN 2',
    'PEASANT DGREEN 3',
    'PEASANT BGREEN 1',
    'PEASANT BGREEN 2',
    'PEASANT BGREEN 3',
    'PEASANT GOLD 1',
    'PEASANT GOLD 2',
    'PEASANT GOLD 3',
    'PEASANT BLUE',
    'ZOMBIE',
    'BECOMING ACOLYTE',
    'ZOMBIE SPAWNER',
    'HUGE TANK 1',
    'HUGE TANK 2',
    'HUGE TANK 3',
    'TANK 4 SPINE WITH ORGANS',
    'TANK 5 STUMPY THE ACOLYTE',
    'TANK 6 SPECTER',
    'KNEELING GUY',
    'BEGGAR 1',
    'BEGGAR 2',
    'BEGGAR 3',
    'BEGGAR 4',
    'BEGGAR 5',
    'REBEL 1',
    'REBEL 2',
    'REBEL 3',
    'REBEL 4',
    'REBEL 5',
    'REBEL 6',
    'MACIL 1',
    'MACIL 2',
    'MT_MISSILESMOKE',
    'REAVER',
    'ACOLYTE 1 TAN',
    'ACOLYTE 2 RED',
    'ACOLYTE 3 RUST',
    'ACOLYTE 4 GRAY',
    'ACOLYTE 5 DARK GREEN',
    'ACOLYTE 6 GOLD',
    'ACOLYTE 7 BRIGHT GREEN',
    'ACOLYTE 8 BLUE',
    'SHADOW ACOLYTE',
    'TEMPLAR',
    'CRUSADER',
    'BISHOP',
    'ORACLE',
    'LOREMASTER',
    'SPECTER A',
    'MT_NODE',
    'MT_SPECTREHEAD',
    'SPECTER B',
    'SPECTER C',
    'SPECTER D',
    'SPECTER E',
    'ENTITY',
    'MT_SUBENTITY',
    'ENTITY NEST',
    'ENTITY POD',
    'MT_SIGIL_B_SHOT',
    'MT_SIGIL_SB_SHOT',
    'MT_SIGIL_C_SHOT',
    'MT_SIGIL_SC_SHOT',
    'MT_SIGIL_E_OFFSHOOT',
    'MT_SIGIL_TRAIL',
    'MT_SIGIL_E_SHOT',
    'MT_SIGIL_SE_SHOT',
    'MT_SIGIL_A_ZAP_LEFT',
    'MT_SIGIL_A_ZAP_RIGHT',
    'MT_SIGIL_A_GROUND',
    'MT_SIGIL_D_SHOT',
    'MT_SIGIL_SD_SHOT',
    'SENTINEL',
    'STALKER',
    'INQUISITOR',
    'MT_INQARM',
    'PROGRAMMER',
    'MT_PROGRAMMERBASE',
    'MT_HOOKSHOT',
    'MT_CHAINSHOT',
    'MT_MINIMISSLE',
    'MT_C_MISSILE',
    'MT_SEEKMISSILE',
    'MT_ELECARROW',
    'MT_POISARROW',
    'MT_R_LASER',
    'MT_L_LASER',
    'MT_HEGRENADE',
    'MT_PGRENADE',
    'MT_INQGRENADE',
    'MT_PFLAME',
    'MT_TORPEDO',
    'MT_TORPEDOSPREAD',
    'MT_SFIREBALL',
    'MT_C_FLAME',
    'MT_STRIFEPUFF3',
    'MT_STRIFEPUFF',
    'MT_SPARKPUFF',
    'MT_BLOOD_DEATH',
    'MT_TFOG',
    'MT_IFOG',
    'TELEPORT DESTINATION',
    'CLAXON WARNING LIGHT',
    'CEILING TURRET',
    'GATES',
    'COMPUTER',
    'MED PATCH',
    'MEDIKIT',
    'SURGERY KIT',
    'DEGNIN ORE',
    'METAL ARMOR',
    'LEATHER ARMOR',
    'WATER BOTTLE',
    'MUG',
    'BASE KEY',
    'MT_GOVSKEY',
    'TRAVEL PASSCARD',
    'BLUE ID CARD',
    'MT_PRISONKEY',
    'SEVERED HAND',
    'MT_POWER1KEY',
    'MT_POWER2KEY',
    'MT_POWER3KEY',
    'GOLD KEY',
    'GOLD ID BADGE',
    'SILVER KEY',
    'ORACLE KEY',
    'MT_MILITARYID',
    'ORDER KEY',
    'WAREHOUSE KEY',
    'BRASS KEY',
    'RED CRYSTAL KEY',
    'BLUE CRYSTAL KEY',
    'CHAPEL KEY',
    'MT_CATACOMBKEY',
    'MT_SECURITYKEY',
    'CORE KEY',
    'MAULER KEY',
    'FACTORY KEY',
    'MINE KEY',
    'MT_NEWKEY5',
    'SHADOW ARMOR',
    'ENVIRONMENTAL SUIT',
    'GUARD UNIFORM',
    'OFFICER UNIFORM',
    'MAP',
    'SCANNER RADAR',
    'TELEPORT BEACON',
    'TARGETER',
    'GOLD COIN',
    '10 GOLD',
    '25 GOLD',
    '50 GOLD',
    'MT_MONY_300',
    'MT_TOKEN_RING',
    'OFFERING CHALICE',
    'MT_TOKEN_EAR',
    'COMMUNICATOR',
    'HE GRENADES',
    'PHOSPHOROUS GRENADES',
    'BULLET CLIP',
    'BOX OF BULLETS',
    'MISSILES',
    'CRATE OF MISSILES',
    'ENERGY POD',
    'ENERGY PACK',
    'POISON ARROWS',
    'ELECTRIC BOLTS',
    'AMMO SATCHEL',
    'ASSAULT GUN',
    'ASSAULT GUN STANDING',
    'FLAME THROWER',
    'MT_TOKEN_FLAME_THROWER_PARTS',
    'MINI MISSILE LAUNCHER',
    'MAULER',
    'CROSSBOW',
    'GRENADE LAUNCHER',
    'SIGIL A LIGHTNING STRIKE',
    'SIGIL B RAIL LIGHTNING SHOT',
    'SIGIL C SPREAD SHOT',
    'SIGIL D COLUMN SHOT',
    'SIGIL E BIG BLAST',
    'POWER CRYSTAL',
    'RAT',
    'WOODEN BARREL',
    'EXPLOSIVE BARREL',
    'PRACTICE TARGET',
    'SILVER FLOURESCENT LIGHT',
    'BRASS FLOURESCENT LIGHT',
    'GOLD FLOURESCENT LIGHT',
    'GLOBE LIGHT',
    'TECHNO PILLAR',
    'AZTEC PILLAR',
    'DAMAGED AZTEC PILLAR',
    'RUINED AZTEC PILLAR',
    'HUGE TECH PILLAR',
    'HUGE ALIEN PILLAR',
    'STALACTITE',
    'SMALL STALACTITE',
    'STALACMITE',
    'CAVE PILLAR TOP',
    'CAVE PILLAR BOTTOM',
    'STALACMITE SMALL',
    'CANDLE',
    'CANDELABRA',
    'FLOOR WATER DRIP',
    'WATERFALL SPLASH',
    'CEILING WATER DRIP',
    'FOUNTAIN',
    'HEARTS IN TANK',
    'TELEPORT SWIRL',
    'DEAD CRUSADER',
    'DISAPPEARING DEAD PLAYER',
    'DISAPPEARING DEAD PEASANT',
    'DISAPPEARING DEAD ACOLYTE',
    'DEAD REAVER',
    'DEAD REBEL',
    'SACRIFICED GUY',
    'MT_GIBS',
    'BURNING BARREL',
    'BURNING BOWL',
    'BURNING BRAZIER',
    'SMALL BURNING TORCH',
    'SMALL UNLIT TORCH',
    'CEILING CHAIN',
    'CAGE LIGHT',
    'STATUE',
    'RUINED STATUE',
    'MEDIUM TORCH',
    'OUTSIDE LAMP',
    'POLE LANTERN',
    'ROCK 1',
    'ROCK 2',
    'ROCK 3',
    'ROCK 4',
    'STICK IN WATER',
    'RUBBLE 1',
    'RUBBLE 2',
    'RUBBLE 3',
    'RUBBLE 4',
    'RUBBLE 5',
    'RUBBLE 6',
    'RUBBLE 7',
    'RUBBLE 8',
    'SURGERY CRAB',
    'LARGE TORCH',
    'HUGE TORCH',
    'PALM TREE',
    'BIG TREE',
    'POTTED TREE',
    'TREE STUB',
    'SHORT BUSH',
    'TALL BUSH',
    'CHIMNEYSTACK',
    'BARRICADE COLUMN',
    'POT',
    'PITCHER',
    'STOOL',
    'METAL POT',
    'TUB',
    'ANVIL',
    'SILVER TECH LAMP',
    'BRASS TECH LAMP',
    'TRAY',
    'AMMO FILLER',
    'SIGIL BANNER',
    'REBEL BOOTS',
    'REBEL HELMET',
    'REBEL SHIRT',
    'POWER COUPLING',
    'BROKEN POWER COUPLING',
    'ALIEN BUBBLE COLUMN',
    'ALIEN FLOOR BUBBLE',
    'ALIEN CEILING BUBBLE',
    'ALIEN ASP CLIMBER',
    'ALIEN SPIDER LIGHT',
    'MT_MEAT',
    'MT_JUNK',
    'MT_BURNDROP',
    'MT_TOKEN_AMMO',
    'MT_TOKEN_HEALTH',
    'MT_TOKEN',
    'MT_TOKEN_ALARM',
    'MT_TOKEN_DOOR1',
    'MT_TOKEN_SHOPCLOSE',
    'MT_TOKEN_PRISON_PASS',
    'MT_TOKEN_DOOR3',
    'MT_TOKEN_STAMINA',
    'MT_TOKEN_NEW_ACCURACY',
    'MT_TOKEN_REPORT',
    'MT_TOKEN_TOUGHNESS',
    'MT_TOKEN_ACCURACY',
    'MT_TOKEN_ORACLE_PASS',
    'MT_TOKEN_QUEST1',
    'MT_TOKEN_QUEST2',
    'MT_TOKEN_QUEST3',
    'MT_TOKEN_QUEST4',
    'MT_TOKEN_QUEST5',
    'MT_TOKEN_QUEST6',
    'MT_TOKEN_QUEST7',
    'MT_TOKEN_QUEST8',
    'MT_TOKEN_QUEST9',
    'MT_TOKEN_QUEST10',
    'MT_TOKEN_QUEST11',
    'MT_TOKEN_QUEST12',
    'MT_TOKEN_QUEST13',
    'MT_TOKEN_CRYSTAL',
    'MT_TOKEN_QUEST15',
    'MT_GATEQUEST',
    'MT_TOKEN_QUEST17',
    'MT_TOKEN_QUEST18',
    'MT_TOKEN_QUEST19',
    'MT_TOKEN_QUEST20',
    'MT_TOKEN_BISHOP',
    'MT_TOKEN_QUEST22',
    'MT_TOKEN_ORACLE',
    'MT_TOKEN_MACIL',
    'MT_TOKEN_QUEST25',
    'MT_TOKEN_LOREMASTER',
    'MT_SECRQUEST',
    'MT_TOKEN_QUEST28',
    'MT_TOKEN_QUEST29',
    'MT_TOKEN_QUEST30',
    'MT_TOKEN_QUEST31',
    'MT_SLIDESHOW',
    'SPLASH',
    'SPLASH 2',
    'LAVA SPLASH',
    'LAVA SMOKE',
    'SLUDGE CHUNK',
    'SLUDGE SPLASH',
    'NUKAGE CHUNK',
    'NUKAGE SPLASH',
    'GREEN BLOOD',
    'BLUE BLOOD',
    'PUSHER',
    'PULLER',
    'NONE'
  );

implementation

end.

